In [1]:
import pandas as pd
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28, 34, None, 30, 29, 40, 25, 32],
    "Salary": [50000, 60000, None, 52000, 49000, 70000, 48000, 58000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89]
}

df=pd.DataFrame(data)
df.head()

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                 85
1       None  34.0  60000.0                 90
2  Ghanshyam   NaN      NaN                 78
3  Dhanshyam  30.0  52000.0                 92
4      Aditi  29.0  49000.0                 88

In [4]:
df.sort_values(by=["Name","Age"],ascending=[True,True], inplace=True)

In [5]:
df.head(8)

        Name   Age   Salary  Performance Score
4      Aditi  29.0  49000.0                 88
3  Dhanshyam  30.0  52000.0                 92
2  Ghanshyam   NaN      NaN                 78
5    Jagdish  40.0  70000.0                 95
6        Raj  25.0  48000.0                 80
0        Ram  28.0  50000.0                 85
7     Simran  32.0  58000.0                 89
1       None  34.0  60000.0                 90

In [9]:
df["Salary"]=df["Salary"].interpolate(method='linear')

In [10]:
avg_salary=df["Salary"].mean()
avg_salary

np.float64(56000.0)