In [2]:
import pandas as pd

data={
    "Name":['Inam Khan',"Kamran Khan","Amir Khan","Salman Khan","Shahrukh Khan"],
    "Age":[34,45,29,40,38],
    "Salary":[70000,80000,60000,75000,72000],
    "City":['Delhi','Mumbai','Chennai','Kolkata','Bangalore']
}


df=pd.DataFrame(data)

In [3]:
df.head()

            Name  Age  Salary       City
0      Inam Khan   34   70000      Delhi
1    Kamran Khan   45   80000     Mumbai
2      Amir Khan   29   60000    Chennai
3    Salman Khan   40   75000    Kolkata
4  Shahrukh Khan   38   72000  Bangalore

In [4]:
df.sort_values(by=["Age","Salary"], ascending=[True,True], inplace = True )

In [5]:
df.head()

            Name  Age  Salary       City
2      Amir Khan   29   60000    Chennai
0      Inam Khan   34   70000      Delhi
4  Shahrukh Khan   38   72000  Bangalore
3    Salman Khan   40   75000    Kolkata
1    Kamran Khan   45   80000     Mumbai