In [3]:
import pandas as pd
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28, 34, None, 30, 29, 40, 25, 32],
    "Salary": [50000, 60000, None, 52000, 49000, 70000, 48000, 58000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89]
}

df=pd.DataFrame(data)
df.head()

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                 85
1       None  34.0  60000.0                 90
2  Ghanshyam   NaN      NaN                 78
3  Dhanshyam  30.0  52000.0                 92
4      Aditi  29.0  49000.0                 88

In [ ]:
df.fillna(0,inplace=True)
df.head()

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                 85
1          0  34.0  60000.0                 90
2  Ghanshyam   0.0      0.0                 78
3  Dhanshyam  30.0  52000.0                 92
4      Aditi  29.0  49000.0                 88

In [6]:
import pandas as pd
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28, 34, None, 30, 29, 40, 25, 32],
    "Salary": [50000, 60000, None, 52000, 49000, 70000, 48000, 58000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89]
}

df=pd.DataFrame(data)
df.head()

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                 85
1       None  34.0  60000.0                 90
2  Ghanshyam   NaN      NaN                 78
3  Dhanshyam  30.0  52000.0                 92
4      Aditi  29.0  49000.0                 88

In [11]:
df['Age'].fillna(df['Age'].mean, inplace=True)

df.head()

        Name        Age   Salary  Performance Score
0        Ram  28.000000  50000.0                 85
1       None  34.000000  60000.0                 90
2  Ghanshyam  31.142857      NaN                 78
3  Dhanshyam  30.000000  52000.0                 92
4      Aditi  29.000000  49000.0                 88