In [3]:
import pandas as pd
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28, 34, None, 30, 29, 40, 25, 32],
    "Salary": [50000, 60000, None, 52000, 49000, 70000, 48000, 58000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89],
    "Value":[1,2,None,4,5,None,7,8]
}

df=pd.DataFrame(data)

df

        Name   Age   Salary  Performance Score  Value
0        Ram  28.0  50000.0                 85    1.0
1       None  34.0  60000.0                 90    2.0
2  Ghanshyam   NaN      NaN                 78    NaN
3  Dhanshyam  30.0  52000.0                 92    4.0
4      Aditi  29.0  49000.0                 88    5.0
5    Jagdish  40.0  70000.0                 95    NaN
6        Raj  25.0  48000.0                 80    7.0
7     Simran  32.0  58000.0                 89    8.0

In [8]:
df["Value"] = df["Value"].interpolate(method='linear')
df

        Name   Age   Salary  Performance Score  Value
0        Ram  28.0  50000.0                 85    1.0
1       None  34.0  60000.0                 90    2.0
2  Ghanshyam   NaN      NaN                 78    3.0
3  Dhanshyam  30.0  52000.0                 92    4.0
4      Aditi  29.0  49000.0                 88    5.0
5    Jagdish  40.0  70000.0                 95    6.0
6        Raj  25.0  48000.0                 80    7.0
7     Simran  32.0  58000.0                 89    8.0

In [ ]:
import pandas as pd
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28, 34, None, 30, 29, 40, 25, 32],
    "Salary": [50000, 60000, None, 52000, 49000, 70000, 48000, 58000],
    "Performance Score": [85, 90, 78, 92, 88, 95, 80, 89],
    "Value":[1,2,None,4,5,None,7,8]
}

df=pd.DataFrame(data)

df

In [11]:
df["Value"] = df["Value"].interpolate(method='polynomial', order=3)
df

        Name   Age   Salary  Performance Score  Value
0        Ram  28.0  50000.0                 85    1.0
1       None  34.0  60000.0                 90    2.0
2  Ghanshyam   NaN      NaN                 78    3.0
3  Dhanshyam  30.0  52000.0                 92    4.0
4      Aditi  29.0  49000.0                 88    5.0
5    Jagdish  40.0  70000.0                 95    6.0
6        Raj  25.0  48000.0                 80    7.0
7     Simran  32.0  58000.0                 89    8.0

In [16]:
df.interpolate(mothod='linear', inplace=True)
df.head()

/var/folders/rh/5xfb27r55ql68l4zwc899mw80000gn/T/ipykernel_5287/2285944269.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(mothod='linear', inplace=True)

        Name   Age   Salary  Performance Score  Value
0        Ram  28.0  50000.0                 85    1.0
1       None  34.0  60000.0                 90    2.0
2  Ghanshyam  32.0  56000.0                 78    3.0
3  Dhanshyam  30.0  52000.0                 92    4.0
4      Aditi  29.0  49000.0                 88    5.0

In [18]:
df['Name'].fillna("Inam",inplace=True)
df.head()

        Name   Age   Salary  Performance Score  Value
0        Ram  28.0  50000.0                 85    1.0
1       Inam  34.0  60000.0                 90    2.0
2  Ghanshyam  32.0  56000.0                 78    3.0
3  Dhanshyam  30.0  52000.0                 92    4.0
4      Aditi  29.0  49000.0                 88    5.0